# 7. Transformation Matrix from Basis B to C
- Deep-ML: https://www.deep-ml.com/problems/35

## Problem statement

- Write a Python function to convert a 1D numpy array into a diagonal matrix. The function should take in a 1D numpy array x and return a 2D numpy array representing the diagonal matrix.

### 🧮 Example

**Input:**
```
x = np.array([1, 2, 3])
output = make_diagonal(x)
print(output)
```

**Output:**
```
[[1. 0. 0.]
[0. 2. 0.]
[0. 0. 3.]]
```

**Reasoning:**
- The input vector [1, 2, 3] is converted into a diagonal matrix where the elements of the vector form the diagonal of the matrix.

## Learn the about the topic

# Understanding Diagonal Matrices

A **diagonal matrix** is a square matrix in which the entries outside the main diagonal are all zero.  
The **main diagonal** is the set of entries extending from the top left to the bottom right of the matrix.

---

## Problem Overview
In this problem, you will write a function to **convert a 1D NumPy array (vector) into a diagonal matrix**.  
The resulting matrix will have the elements of the input vector on its **main diagonal**, with **zeros elsewhere**.

---

## Mathematical Representation

markdown
'''
Given a vector:

\[
x = [x_1, x_2, \dots, x_n]
\]

The corresponding diagonal matrix \( D \) is:

\[
D = \begin{bmatrix}
x_1 & 0 & 0 & \cdots & 0 \\
0 & x_2 & 0 & \cdots & 0 \\
0 & 0 & x_3 & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
0 & 0 & 0 & \cdots & x_n \\
\end{bmatrix}
\]
'''
---

## Importance

Diagonal matrices are important in various **mathematical** and **scientific** computations due to their **simple structure** and **useful properties**:

- **Easy to compute powers** (e.g., \( D^k \) is simply each diagonal element raised to the \( k \)-th power).
- **Fast matrix multiplication** (only the diagonal elements matter).
- **Useful in eigenvalue problems** — especially in diagonalization processes.
- **Appears in machine learning** for tasks like covariance matrices after PCA (Principal Component Analysis).


## Solution

In [1]:
import numpy as np

def make_diagonal(x):
	return np.diag(x)
	# Your code here
	

# Example usage:
x = np.array([1, 2, 3])
output = make_diagonal(x)
output

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

## QnA

## 1. 